UnitRegistry package for assigning standard unit varibles

In [2]:
from pint import UnitRegistry

unit = UnitRegistry()

distance = 5 * unit.meter
time = 2 * unit.second
speed = distance / time
print(speed)

2.5 meter / second


In [ ]:
"""
SI PREFIXES

Prefix     Symbol     Power of 10
----------------------------------
quecto       q          10^-30
ronto        r          10^-27
yocto        y          10^-24
zepto        z          10^-21
atto         a          10^-18
femto        f          10^-15
pico         p          10^-12
nano         n          10^-9
micro        μ          10^-6
milli        m          10^-3
centi        c          10^-2
deci         d          10^-1
BASE                    10^0
deka         da         10^1
hecto        h          10^2
kilo         k          10^3
mega         M          10^6
giga         G          10^9
tera         T          10^12
peta         P          10^15
exa          E          10^18
zetta        Z          10^21
yotta        Y          10^24
ronna        R          10^27
quetta       Q          10^30

"""

# Excercise

1, 2, 3, 4, 5, 17, 18, 21, 24, 26, 29, 31, 32

## 1. expression conversion

In [15]:
print(10**6, 'phones'); print(10**-6, 'phones');
print(10**12, 'bulls'); print(10**-2, 'pedes'); print(10**-12, 'boots');

1000000 phones
1e-06 phones
1000000000000 bulls
0.01 pedes
1e-12 boots


## 2. SI conversion

In [16]:
# a)
unit.define("dollars= [currency]")
time = (365 / 7) * unit.weeks
salary = 36000 * unit.dollars

# salary = weekly_pay * time 
weekly_wage = salary / time 

round(weekly_wage, 2)


<Quantity(690.41, 'dollars / week')>

In [20]:
# b) 
prize = 10 * 10**6 * unit.dollars # mega = 10^6
time = 20 * unit.years

monthly_salaries = prize / time.to(unit.months)
round(monthly_salaries, 2)

<Quantity(41666.67, 'dollars / month')>

In [26]:
unit.define("words = [code]")
capacity = 30 * unit.gigabytes
read_rate = (8 * unit.bytes) / unit.words

word_count = capacity.to(unit.byte) / read_rate
word_count


<Quantity(3.75e+09, 'words')>

The Standard of Time

## 3. microncentury

In [50]:
import pint

unit = pint.UnitRegistry()

unit.define("century = 100 * year")

lecture = 50 * unit.minute
microcentury = 1e-6 * unit.century

ratio = (lecture / microcentury).to_reduced_units()

print(round(ratio.magnitude * 100, 2), "%")

95.06 %


## 4. Circumference of the Earth

Time different between the 

In [4]:
distance = 3000 * unit.miles
hours = 3 * unit.hours
earth_time = 24 * unit.hours

earth_cir = (distance / hours) * earth_time
print(earth_cir)

24000.0 mile


## 5. Seconds in a year

%error = (abs.(approximate - actual) / actual ) * 100%

In [13]:
import math

time = 1 * unit.years
time = time.to(unit.second)

number = math.pi * 10**7 * unit.seconds
difference = abs(number - time)
ratio = difference / time 
percentage = ratio * 100
print(round(percentage.magnitude, 3), "%")


0.449 %


## 17. Earth

In [43]:
earth_radius = 6.37e6 * unit.meters
earth_radius = earth_radius.to(unit.kilometer)

surface_area = 4 * math.pi * earth_radius**2
volume = (4/3) * math.pi * earth_radius**3

print(f"Earth radius: {earth_radius.magnitude:.3g} km")
print(f"Surface area: {surface_area.magnitude:.3g} km²")
print(f"Volume: {volume.magnitude:.3g} km³")

Earth radius: 6.37e+03 km
Surface area: 5.1e+08 km²
Volume: 1.08e+12 km³


## 18. m/s conversion

In [30]:
animals = {
    "squirrel": 19 * unit.kilometer / unit.hour,
    "rabbit": 30 * unit.knot,
    "snail": 0.030 * unit.mile / unit.hour,
    "spider": 1.8 * unit.foot / unit.second,
    "cheetah": 1.9 * unit.kilometer / unit.minute,
    "human": 1000 * unit.centimeter / unit.second,
    "fox": 1100 * unit.meter / unit.minute,
    "lion": 1900 * unit.kilometer / unit.day
}

for animal, speed in animals.items():
    print(animal, round(speed.to(unit.meter / unit.second), 4))


squirrel 5.2778 meter / second
rabbit 15.4333 meter / second
snail 0.0134 meter / second
spider 0.5486 meter / second
cheetah 31.6667 meter / second
human 10.0 meter / second
fox 18.3333 meter / second
lion 21.9907 meter / second


## 21. Astronomical measurement

In [71]:
au = 1 * unit.astronomical_unit
parsec = 1 * unit.parsec
light_year = 1 * unit.light_year

au_to_par = au.to(unit.parsec)
au_to_light = au.to(unit.light_year)
print("a)")
print(f"1 AU to parsec: {au_to_par.magnitude:.3g} {au_to_par.units}")
print(f"1 Au to ligt-year: {au_to_light.magnitude:.3g} {au_to_light.units}")

par_to_km = parsec.to(unit.kilometer)
light_to_km = light_year.to(unit.kilometer)
print("b)")
print(f"1 ligh_year to km: {light_to_km.magnitude:.3g} {light_to_km.units}")
print(f"1 parsec to km: {par_to_km.magnitude:.3g} {par_to_km.units}")


a)
1 AU to parsec: 4.85e-06 parsec
1 Au to ligt-year: 1.58e-05 light_year
b)
1 ligh_year to km: 9.46e+12 kilometer
1 parsec to km: 3.09e+13 kilometer


## 24. H20, in the ocean

In [99]:
h2o_mass = (2 + 16) * unit.atomic_mass_constant
h2o_kilogram = h2o_mass.to(unit.kilogram)
print("a)")
print(f"{h2o_kilogram.magnitude:.2g} {h2o_kilogram.units}")
print("b)")
ocean_mass = 1.4e21 * unit.kilogram
num_of_h20 = ocean_mass / h2o_kilogram 
print(f"Number of H20 in the oceans of the world: {num_of_h20.magnitude:.3g} H20")

a)
3e-26 kilogram
b)
Number of H20 in the oceans of the world: 4.68e+46 H20


## 26. Mass of air

In [111]:
room_volume = (21 * unit.feet) * (13 * unit.feet) * (12 * unit.feet)
density = 1.21 * (unit.kilogram / (unit.meter)**3)

mass = (room_volume * density).to(unit.kilogram) 
print(f"Mass of the air in the room: {mass.magnitude:.2f} {mass.units}(s)")

Mass of the air in the room: 112.25 kilogram(s)


## 29 Wavelenght

In [112]:
wavelength = (1 / 1650763.73) * unit.meter
wavelength_nm = wavelength.to(unit.nanometer) 

print(f"{wavelength_nm.magnitude:.3f} {wavelength_nm.units}")

605.780 nanometer


## 31 Dimesiona analysis

In [115]:
# V / t = K * A * H * L^-1
V = (1 * unit.meter) ** 3
t = 1 * unit.second

A = 1 * (unit.meter) ** 2
H = 1 * unit.meter
L = 1 * unit.meter

K = ( V / t) / ((A * H) / L)

print(K.units)


meter / second


## 32. Planck time 33. Planck mass

In [ ]:
import numpy as np

G = 6.67e-11 * unit.meter**3 / (unit.kilogram * unit.second**2)
h = 6.63e-34 * unit.kilogram * unit.meter**2 / unit.second
c = 3.00e8 * unit.meter / unit.second

constants = [c, G, h]

# Rows   = Mass, Length, Time
# Column = c, G, h
dimensions = np.array([
    [
        quantity.dimensionality.get("[mass]", 0),
        quantity.dimensionality.get("[length]", 0),
        quantity.dimensionality.get("[time]", 0)
    ]
    for quantity in constants
]).T

print("Dimension matrix:")
print(dimensions)


#    M^0 L^0 T^1
target_time = np.array([0, 0, 1])

a, b, d = np.linalg.solve(dimensions, target_time)

planck_time = c**a * G**b * h**d

print("\nPlanck Time")
print(f"Exponents: c={a}, G={b}, h={d}")
print(f"Result: {planck_time:.3e}")






#    M^1 L^0 T^0
target_mass = np.array([1, 0, 0])

a, b, d = np.linalg.solve(dimensions, target_mass)

planck_mass = c**a * G**b * h**d

print("\nPlanck Mass")
print(f"Exponents: c={a}, G={b}, h={d}")
print(f"Result: {planck_mass:.3e}")

Dimension matrix:
[[ 0 -1  1]
 [ 1  3  2]
 [-1 -2 -1]]

Planck Time
Exponents: c=-2.5, G=0.5, h=0.5
Result: 1.349e-43 second

Planck Mass
Exponents: c=0.5, G=-0.5, h=0.5
Result: 5.461e-08 kilogram
